fix: linkedin and slack signin
weweb-assets/plugin-supabase-auth pull request #34
Opened 2024-08-20 14:11 UTC by AlexisJC

2024-08-26 16:13 UTC, AurelieV approved these changes

2024-08-27 07:53 UTC, Dams-d approved these changes

2024-08-27 07:54 UTC, Dams-d requested changes
Can you fix the icons too? It should be something like logos/google

2024-08-27 08:20 UTC, kevinbarfleur approved these changes

2024-08-27 09:22 UTC, MarcFabre commented
@Dams-d I added the icons and made a new PR in the editor : https://github.com/weweb-team/weweb-editor/pull/3187

2024-08-27 09:30 UTC, Dams-d approved these changes

2024-08-27 13:52 UTC, merged